shallow_clone: true

os:
  - Visual Studio 2015

environment:
  matrix:
  - TOOLSET: vs2010
    GENERATOR: Visual Studio 10 2010 Win64
  - TOOLSET: vs2013
    GENERATOR: Visual Studio 12 2013 Win64
  - TOOLSET: vs2015
    GENERATOR: Visual Studio 14 2015 Win64

install:
  # Download Premake
  - ps: Start-FileDownload 'https://github.com/premake/premake-core/releases/download/v5.0.0-alpha7/premake-5.0.0-alpha7-windows.zip' 'premake.zip'
  
  # Extract it in-place; premake5.exe is at the top level.
  - 7z x premake.zip

  # Download SDL.
  - ps: Start-FileDownload 'https://www.libsdl.org/release/SDL2-devel-2.0.4-VC.zip' 'RecastDemo/Contrib/SDL.zip'

  # Extract it, put it in the right place, and rename it.
  - cd RecastDemo\Contrib && 7z x SDL.zip && ren SDL2-2.0.4 SDL && cd ..\..

  # Generate solution files using premake.
  - cd RecastDemo && "../premake5.exe" %TOOLSET% && cd ..

configuration:
  - Debug
  - Release

build:
  project: RecastDemo/Build/$(TOOLSET)/recastnavigation.sln

after_build:
  - mkdir build
  - cd build
  - cmake -G "%GENERATOR%" -D RECASTNAVIGATION_STATIC=ON -D SDL2_ROOT_DIR="%cd%\..\RecastDemo\Contrib\SDL" ..
  - cmake --build . -- /m:%NUMBER_OF_PROCESSORS%
  - ctest -V
  - cd ..

after_test:
  - RecastDemo\Bin\Tests.exe
